@echo off
REM Setup script for ai_ops native Claude Code subagent definitions
REM (.claude\agents\*.md), generated by 00_Admin\scripts\regenerate_profiles.py.
REM
REM Closes G-12 (command-surface-uplift bundle, 2026-09-06): the generator
REM always writes to the ai_ops repo tree; this script is the install step
REM that additionally places those files at a workspace root when this repo
REM is nested inside a larger multi-repo workspace, mirroring
REM setup_claude_skills.bat's --workspace/--repo pattern.

setlocal enableextensions enabledelayedexpansion

REM Capture the script's own location BEFORE the arg-parse loop runs.
REM Plain `shift` shifts %0 along with %1-%9 in Windows batch, so if this
REM block ran after parsing, %~f0 would resolve to whatever the last
REM parsed flag's text was instead of this script's real path (found by
REM round-5 independent review, 2026-09-07; reproduced independently by
REM round-6 review with its own fixture).
set "SCRIPT_DIR="
for %%I in ("%~f0") do set "SCRIPT_DIR=%%~dpI"
for %%I in ("!SCRIPT_DIR!..\..") do set "REPO_ROOT=%%~fI"
set "REPO_AGENTS_DIR=!REPO_ROOT!\.claude\agents"

set "scope=repo"
set "dry_run=0"
set "assume_yes=0"
set "force=0"

:parse_args
if "%~1"=="" goto args_done
if /I "%~1"=="--workspace" (set "scope=workspace" & shift & goto parse_args)
if /I "%~1"=="-w" (set "scope=workspace" & shift & goto parse_args)
if /I "%~1"=="--repo" (set "scope=repo" & shift & goto parse_args)
if /I "%~1"=="-n" (set "dry_run=1" & shift & goto parse_args)
if /I "%~1"=="--dry-run" (set "dry_run=1" & shift & goto parse_args)
if /I "%~1"=="-y" (set "assume_yes=1" & shift & goto parse_args)
if /I "%~1"=="--yes" (set "assume_yes=1" & shift & goto parse_args)
if /I "%~1"=="-f" (set "force=1" & shift & goto parse_args)
if /I "%~1"=="--force" (set "force=1" & shift & goto parse_args)
if /I "%~1"=="-h" goto usage
if /I "%~1"=="--help" goto usage
echo Unknown option: %~1
goto usage_error

:args_done
where python >nul 2>&1
if errorlevel 1 (
  echo Python is required to run regenerate_profiles.py.
  exit /b 1
)

echo Regenerating native subagent definitions via regenerate_profiles.py...
if "!dry_run!"=="1" (
  python "!REPO_ROOT!\00_Admin\scripts\regenerate_profiles.py" --dry-run
) else (
  python "!REPO_ROOT!\00_Admin\scripts\regenerate_profiles.py"
)
if errorlevel 1 (
  echo Subagent profile generation failed; not proceeding to install.
  exit /b 1
)

if /I not "!scope!"=="workspace" (
  echo.
  echo Repo-scope install complete. Subagent definitions are at !REPO_AGENTS_DIR!\.
  echo ^(and plugins\ai-ops-governance\agents\, tracked in the repo^).
  endlocal
  exit /b 0
)

for %%I in ("!REPO_ROOT!\..") do set "WORKSPACE_ROOT=%%~fI"
set "WORKSPACE_AGENTS_DIR=!WORKSPACE_ROOT!\.claude\agents"

echo.
echo Workspace scope: copying to !WORKSPACE_AGENTS_DIR!\

if "!dry_run!"=="1" (
  for %%f in ("!REPO_AGENTS_DIR!\*.md") do echo Would copy: %%~nxf -^> !WORKSPACE_AGENTS_DIR!\
  endlocal
  exit /b 0
)

set "has_entries="
if exist "!WORKSPACE_AGENTS_DIR!" (
  for /f %%A in ('dir /b "!WORKSPACE_AGENTS_DIR!" 2^>nul') do set "has_entries=1"
)
if defined has_entries if "!assume_yes!"=="0" if not "!force!"=="1" (
  echo Found existing files in !WORKSPACE_AGENTS_DIR!.
  choice /M "Overwrite with the current repo-generated set"
  if errorlevel 2 (
    echo Cancelled ^(repo-scope files already written^).
    endlocal
    exit /b 0
  )
)

if not exist "!WORKSPACE_AGENTS_DIR!" mkdir "!WORKSPACE_AGENTS_DIR!"
copy /Y "!REPO_AGENTS_DIR!\*.md" "!WORKSPACE_AGENTS_DIR!\" >nul
if errorlevel 1 (
  echo Copy to !WORKSPACE_AGENTS_DIR! failed.
  exit /b 1
)

echo Installed subagent definitions to !WORKSPACE_AGENTS_DIR!\.
echo Re-run this script ^(--workspace --force^) after any profile change to keep the workspace copy in sync. /profiles' own Steps now include this same command as its workspace-sync step, so running /profiles after a profile edit has the same effect -- see .ai_ops\workflows\profiles.md.

endlocal
exit /b 0

:usage
echo Usage:
echo   .ai_ops\setup\setup_claude_agents.bat [--workspace^|--repo] [--force] [--dry-run] [--yes]
echo.
echo Options:
echo   -w, --workspace        Also install to workspace root .claude\agents\ ^(cross-repo access^)
echo       --repo             Install to ai_ops repo .claude\agents\ only ^(default^)
echo   -f, --force            Overwrite existing files at the workspace target
echo   -n, --dry-run          Preview actions without writing files
echo   -y, --yes              Non-interactive mode; skip confirmation prompt
echo   -h, --help             Show this help
endlocal
exit /b 0

:usage_error
call :usage
exit /b 1
