#!/bin/sh
# Setup script for ai_ops native Claude Code subagent definitions
# (.claude/agents/*.md), generated by 00_Admin/scripts/regenerate_profiles.py.
#
# Closes G-12 (command-surface-uplift bundle, 2026-09-06): the generator
# always writes to the ai_ops repo tree; this script is the install step
# that additionally places those files at a workspace root when this repo
# is nested inside a larger multi-repo workspace, mirroring
# setup_claude_skills.sh's --workspace/--repo pattern.

set -e

print_usage() {
  cat <<EOF
Usage:
  ./.ai_ops/setup/setup_claude_agents.sh [--workspace|--repo] [--force] [--dry-run] [--yes]

Options:
  -w, --workspace        Also install to workspace root .claude/agents/ (cross-repo access)
      --repo             Install to ai_ops repo .claude/agents/ only (default)
  -f, --force            Overwrite existing files at the workspace target
  -n, --dry-run          Preview actions without writing files
  -y, --yes              Non-interactive mode; skip confirmation prompt
  -h, --help             Show this help

Examples:
  Workspace install (recommended for multi-repo workspaces):
    ./.ai_ops/setup/setup_claude_agents.sh --workspace --force
  Repo install (default):
    ./.ai_ops/setup/setup_claude_agents.sh
  Preview only:
    ./.ai_ops/setup/setup_claude_agents.sh --dry-run

Notes:
  The repo-tree copy (plugins/ai-ops-governance/agents/, .claude/agents/ at
  the repo root) is always produced by regenerate_profiles.py regardless of
  scope; --workspace additionally copies the repo-root .claude/agents/
  output to the workspace root so subagent types are reachable from a
  session launched at the workspace root.
EOF
}

scope="repo"
dry_run="0"
assume_yes="0"
force="0"

while [ $# -gt 0 ]; do
  case "$1" in
    -w|--workspace) scope="workspace" ;;
    --repo)         scope="repo" ;;
    -n|--dry-run)   dry_run="1" ;;
    -y|--yes)       assume_yes="1" ;;
    -f|--force)     force="1" ;;
    -h|--help)      print_usage; exit 0 ;;
    *)
      echo "Unknown option: $1"
      print_usage
      exit 1
      ;;
  esac
  shift
done

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)"
REPO_AGENTS_DIR="$REPO_ROOT/.claude/agents"

py_cmd=""
if command -v python >/dev/null 2>&1; then
  py_cmd="python"
elif command -v python3 >/dev/null 2>&1; then
  py_cmd="python3"
else
  echo "Python is required to run regenerate_profiles.py."
  exit 1
fi

echo "Regenerating native subagent definitions via regenerate_profiles.py..."
if [ "$dry_run" = "1" ]; then
  "$py_cmd" "$REPO_ROOT/00_Admin/scripts/regenerate_profiles.py" --dry-run
else
  "$py_cmd" "$REPO_ROOT/00_Admin/scripts/regenerate_profiles.py"
fi

if [ "$scope" != "workspace" ]; then
  echo ""
  echo "Repo-scope install complete. Subagent definitions are at $REPO_AGENTS_DIR/."
  echo "(and plugins/ai-ops-governance/agents/, tracked in the repo)."
  exit 0
fi

WORKSPACE_ROOT="$(CDPATH= cd -- "$REPO_ROOT/.." && pwd)"
WORKSPACE_AGENTS_DIR="$WORKSPACE_ROOT/.claude/agents"

echo ""
echo "Workspace scope: copying to $WORKSPACE_AGENTS_DIR/"

if [ "$dry_run" = "1" ]; then
  for f in "$REPO_AGENTS_DIR"/*.md; do
    echo "Would copy: $(basename "$f") -> $WORKSPACE_AGENTS_DIR/"
  done
  exit 0
fi

if [ -d "$WORKSPACE_AGENTS_DIR" ] && [ -n "$(ls -A "$WORKSPACE_AGENTS_DIR" 2>/dev/null)" ] \
   && [ "$assume_yes" != "1" ] && [ "$force" != "1" ]; then
  printf "Found existing files in %s/. Overwrite with the current repo-generated set? (y/N): " "$WORKSPACE_AGENTS_DIR"
  read -r response
  case "$response" in
    y|Y) ;;
    *) echo "Cancelled (repo-scope files already written)."; exit 0 ;;
  esac
fi

mkdir -p "$WORKSPACE_AGENTS_DIR"
for f in "$REPO_AGENTS_DIR"/*.md; do
  cp "$f" "$WORKSPACE_AGENTS_DIR/$(basename "$f")"
done

echo "Installed subagent definitions to $WORKSPACE_AGENTS_DIR/."
echo "Re-run this script (--workspace --force) after any profile change to keep the workspace copy in sync. /profiles' own Steps now include this same command as its workspace-sync step, so running /profiles after a profile edit has the same effect -- see .ai_ops/workflows/profiles.md."
